# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test

    # Upload the dist folder as an artifact
    - name: Upload dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-folder
        path: dist/

    # Download the dist folder artifact
    - name: Download dist folder artifact
      uses: actions/download-artifact@v5
      with:
        name: dist-folder
        path: downloaded-dist

    # Log the contents of the downloaded dist folder
    - name: List contents of downloaded dist folder
      run: ls -lR downloaded-dist